
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".

Lmod has detected the following error: Unable to load module because of error
when evaluating modulefile:

/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/Core/llvm/13.0.1.lua:
Empty or non-existent file
     Please check the modulefile and especially if there is a line number
specified in the above message 
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    llvm/13.0.1      /cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/Core/llvm/13.0.1.lua

/var/spool/slurmd/job4019907/slurm_script: line 11: /cvmfs/soft.computecanada.ca/custom/bin/virtualenv: Input/output error
/var/spool/slurmd/job4019907/slurm_script: line 12: /localscratch/kyang.4019907.0/env/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 44, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 32, in <module>
    from pip import pep425tags
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 321, in <module>
    supported_tags = get_supported()
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 284, in get_supported
    elif platform is None and is_manylinux1_compatible():
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 155, in is_manylinux1_compatible
    import _manylinux
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 5] Input/output error: '/cvmfs/soft.computecanada.ca/custom/python/site-packages/_manylinux.py'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 44, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 32, in <module>
    from pip import pep425tags
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 321, in <module>
    supported_tags = get_supported()
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 284, in get_supported
    elif platform is None and is_manylinux1_compatible():
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 155, in is_manylinux1_compatible
    import _manylinux
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 5] Input/output error: '/cvmfs/soft.computecanada.ca/custom/python/site-packages/_manylinux.py'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 44, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 32, in <module>
    from pip import pep425tags
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 321, in <module>
    supported_tags = get_supported()
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 284, in get_supported
    elif platform is None and is_manylinux1_compatible():
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 155, in is_manylinux1_compatible
    import _manylinux
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 5] Input/output error: '/cvmfs/soft.computecanada.ca/custom/python/site-packages/_manylinux.py'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 44, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 32, in <module>
    from pip import pep425tags
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 321, in <module>
    supported_tags = get_supported()
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 284, in get_supported
    elif platform is None and is_manylinux1_compatible():
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 155, in is_manylinux1_compatible
    import _manylinux
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 5] Input/output error: '/cvmfs/soft.computecanada.ca/custom/python/site-packages/_manylinux.py'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 44, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.6/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.6/site-packages/pip/index.py", line 31, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 32, in <module>
    from pip import pep425tags
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 321, in <module>
    supported_tags = get_supported()
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 284, in get_supported
    elif platform is None and is_manylinux1_compatible():
  File "/usr/lib/python3.6/site-packages/pip/pep425tags.py", line 155, in is_manylinux1_compatible
    import _manylinux
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 5] Input/output error: '/cvmfs/soft.computecanada.ca/custom/python/site-packages/_manylinux.py'
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

/var/spool/slurmd/job4019907/slurm_script: line 33: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/lscpu: Input/output error
running ABIDE_poly3_diagnosis_MI_tri_scott_MLPClassifier.py
Traceback (most recent call last):
  File "ABIDE_poly3_diagnosis_MI_tri_scott_MLPClassifier.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
